version: "3"
services:
    app:
        build: .
        restart: always
        ports:
            - "3000:3000"
        container_name: api
        depends_on:
            - db
        command: bash -c "npx prisma migrate reset --force && npm start"
        networks:
            - app_network
    db:
        image: mysql:5.7
        restart: always
        container_name: mysqlDB
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        expose:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - app_network
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "mysqladmin ping -h 127.0.0.1 -u${MYSQL_USER} -p${MYSQL_PASSWORD}",
                ]
            interval: 10s
            retries: 5
volumes:
    db_data:
networks:
    app_network:
        external: true
