export const companyName = [
    "Swift Wing",
    "Tech Grove",
    "Bright Path",
    "Nexus Wave",
    "Sky Glider",
    "Pixel Stream",
    "Energy Boost",
    "Crystal Glow",
    "Solaris Tech",
    "Aqua Tech",
    "Terra Firm",
    "Vital Blend",
    "Prime Sync",
    "Wonder Works",
    "Dream Quest",
    "Echo Loop",
    "Life Spark",
    "Quantum Leap",
    "Fire Fly",
    "Zenith Peak",
];

export const companyNum = [
    "0888111001",
    "0888111002",
    "0888111003",
    "0888111004",
    "0888111005",
    "0888111006",
    "0888111007",
    "0888111008",
    "0888111009",
    "0888111010",
    "0888111011",
    "0888111012",
    "0888111013",
    "0888111014",
    "0888111015",
    "0888111016",
    "0888111017",
    "0888111018",
    "0888111019",
    "0888111020",
];

export const companyCode = [
    "CSW",
    "CTG",
    "CBP",
    "CNW",
    "CSG",
    "CPS",
    "CEB",
    "CCG",
    "CST",
    "CAT",
    "CTF",
    "CVB",
    "CPR",
    "CWW",
    "CDQ",
    "CEL",
    "CLS",
    "CQL",
    "CFF",
    "CZP",
];

export const address = [
    "545 Village Green Way",
    "4028 Meadow Vale Plaza",
    "30206 Jenna Hill",
    "7681 American Center",
    "95005 Straubel Park",
    "6 Petterle Circle",
    "5 Warner Alley",
    "76 Mayer Park",
    "43 Ronald Regan Terrace",
    "64072 Hudson Center",
    "5204 Rowland Drive",
    "74915 Thompson Street",
    "03 Buell Junction",
    "6716 Kenwood Hill",
    "9945 Roxbury Avenue",
    "689 New Castle Way",
    "2561 Rowland Point",
    "5746 Acker Court",
    "31815 Lerdahl Trail",
    "3048 Melvin Street",
];

export const items = [
    "Travel coffee mug",
    "Multi-tool keychain",
    "Reusable shopping bags",
    "Portable phone charger",
    "Bluetooth headphones",
    "Insulated water bottle",
    "Compact umbrella",
    "Desk organizer",
    "Portable Bluetooth speaker",
    "Waterproof phone case",
    "Wireless computer mouse",
    "Laptop sleeve",
    "Magnetic refrigerator organizer",
    "Cable management clips",
    "Collapsible food storage containers",
    "Non-slip bath mat",
    "Foldable laundry hamper",
    "Desk lamp with USB charging port",
    "Dry erase board",
    "Sleep mask",
    "Resistance bands",
    "Selfie stick",
    "Silicone kitchen utensil set",
    "Travel pillow",
    "Wall-mounted coat rack",
    "Bedside caddy organizer",
    "Portable clothes steamer",
    "Cordless electric kettle",
    "Remote control holder",
    "Collapsible silicone straws",
    "Aromatherapy diffuser",
    "Touchscreen gloves",
    "Hanging shoe organizer",
    "Emergency roadside kit",
    "LED flashlight",
    "Handheld vacuum cleaner",
    "Travel toiletry bag",
    "Desk fan",
    "Compact sewing kit",
    "Portable Bluetooth keyboard",
];

export const kodeBarang = [
    "TCM",
    "MTKC",
    "RSBS",
    "PPC",
    "BTH",
    "IWB",
    "CUMB",
    "DOG",
    "PBS",
    "WPC",
    "WCM",
    "LPSV",
    "MROG",
    "CMCL",
    "CFSC",
    "NSBM",
    "FLH",
    "DLCP",
    "DEB",
    "SLM",
    "RBND",
    "SFSK",
    "SKUS",
    "TRPL",
    "WMCR",
    "BCOG",
    "PCS",
    "CEK",
    "RCH",
    "CSS",
    "ADFR",
    "TSG",
    "HSO",
    "ERK",
    "LFL",
    "HVC",
    "TTB",
    "DFAN",
    "CSKT",
    "PBKB",
];
